// ─────────────────────────────────────────────────────────
//  Email sending via Firebase Cloud Function + Resend
//  Sender: Matai Registry <onboarding@resend.dev>
// ─────────────────────────────────────────────────────────
import { getFunctions, httpsCallable } from "firebase/functions";
import { app } from "../firebase";

const functions = getFunctions(app, "australia-southeast1");
const sendNotificationFn = httpsCallable(functions, "sendNotification");

/**
 * Build a clean HTML email body from plain text report
 */
function buildHtml(subject, textBody, generatedBy) {
  const lines = textBody.split("\n").map(l => {
    if (l.startsWith("─")) return `<hr style="border:none;border-top:1px solid #ddd;margin:12px 0"/>`;
    if (l.match(/^\d+\./)) return `<p style="margin:4px 0 0;font-weight:600;color:#1a5c35">${l}</p>`;
    if (l.startsWith("   ")) return `<p style="margin:1px 0 0;padding-left:16px;color:#444;font-size:13px">${l.trim()}</p>`;
    if (l === "") return `<p style="margin:6px 0"></p>`;
    return `<p style="margin:3px 0;color:#333">${l}</p>`;
  }).join("");

  return `<!DOCTYPE html>
<html><head><meta charset="UTF-8"/></head>
<body style="font-family:Georgia,serif;max-width:680px;margin:0 auto;padding:24px;background:#fff;color:#1a1208">
  <div style="border-top:4px solid #1a5c35;padding-top:20px;margin-bottom:24px">
    <p style="font-size:10px;letter-spacing:0.2em;text-transform:uppercase;color:#1a5c35;margin-bottom:6px">
      Matagaluega o Faamasinoga ma le Faafoeina o Tulaga Tau Faamasinoga
    </p>
    <h1 style="font-size:20px;color:#1a1208;margin:0">${subject}</h1>
    <p style="font-size:12px;color:#888;margin-top:6px">Generated by ${generatedBy} · ${new Date().toLocaleDateString("en-GB",{day:"2-digit",month:"long",year:"numeric"})}</p>
  </div>
  <div style="font-size:14px;line-height:1.7">${lines}</div>
  <div style="margin-top:32px;padding-top:16px;border-top:1px solid #eee;font-size:11px;color:#aaa;text-align:center">
    Matai Registry — Resitalaina o Matai — Confidential<br/>
    <a href="https://amiliontechnology-bit.github.io/matai-registry" style="color:#1a5c35">Open Registry</a>
  </div>
</body></html>`;
}

/**
 * Send a notification email via Firebase Function → Resend
 * @returns {{ success: boolean, message: string }}
 */
export async function sendNotificationEmail({ toEmail, subject, textBody, generatedBy = "System" }) {
  try {
    const htmlBody = buildHtml(subject, textBody, generatedBy);
    const result = await sendNotificationFn({ toEmail, subject, htmlBody, textBody });
    return { success: true, message: `✓ Email sent to ${toEmail}` };
  } catch (err) {
    // If function not deployed yet — fall back to mailto
    if (err.code === "functions/not-found" || err.code === "functions/internal") {
      const encoded = encodeURIComponent(textBody);
      const subEnc  = encodeURIComponent(subject);
      window.location.href = `mailto:${toEmail}?subject=${subEnc}&body=${encoded}`;
      return { success: true, message: "✓ Email client opened (function not deployed yet)." };
    }
    throw err;
  }
}
